variable "sgname" {}
variable "ipblock" {}
variable "ins-tag" {}
variable "devami" {}
variable "pub_subnet" {}
variable "pri_subnet" {}
variable "pri_sub_tag" {}
variable "ins_type" {}
variable "sg-tag" {}
variable "pub-sub-tag" {}
variable "devvpc" {}
variable "vpc-tag" {}
variable "devigw" {}
variable "routetag" {}
variable "pub_pri_Ip" {}
variable "pri_pri_Ip" {}
variable "pub_sub_2" {}
variable "pub_sub_3" {}
variable "vol_size" {}
variable "az_zone" {}
variable "eksname" {}
variable "eksversion" {}
variable "ekstag" {}
